EjemploPersona/EjemploPersona/Models/Persona.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EjemploPersona.Models
{
    public class Persona
    {
        private int id;
        [Required]
        private string nombre;
        [Required]
        private string apellido;
        [Required]
        private int dni;
        [Required]
        private int edad;

        public int Id { get => id; set => id = value; }
        public string Nombre { get => nombre; set => nombre = value; }
        public string Apellido { get => apellido; set => apellido = value; }
        public int Dni { get => dni; set => dni = value; }
        public int Edad { get => edad; set => edad = value; }
    }
}

EjemploPersona/EjemploPersona/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EjemploPersona.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

EjemploPersona/EjemploPersona/Controllers/PersonaController.cs
using EjemploPersona.AccesoDatos;
using EjemploPersona.Models;
using EjemploPersona.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EjemploPersona.Controllers
{
    public class PersonaController : Controller
    {
        // GET: Persona
        public ActionResult CargarPersona()
        {
            List<SexoItemVM> listaSexos = AD_Persona.obtenerListaSexos();

            List<SelectListItem> lista = listaSexos.ConvertAll(s =>
            {
                return new SelectListItem()
                {
                    Text = s.Nombre,
                    Value = s.IdSexo.ToString(),
                    Selected = false
                };
            });

            ViewBag.items = lista;
            return View();
        }
        [HttpPost]
        public ActionResult CargarPersona(Persona model)
        {
            if (ModelState.IsValid)
            {
                bool resultado = AD_Persona.Insertar(model);
                if (resultado)
                {
                    return RedirectToAction("ListaPersona", "Persona");
                }
                else
                {
                    return View(model);
                }
            }
            else
            {
                return View(model);
            }
            
        }
        public ActionResult ListaPersona()
        {
            List<Persona> lista = AD_Persona.obtenerListaPersona();
            return View(lista);
        }
        public ActionResult DatosPersona(int idPersona)
        {
            List<SexoItemVM> listaSexos = AD_Persona.obtenerListaSexos();

            List<SelectListItem> lista = listaSexos.ConvertAll(s =>
            {
                return new SelectListItem()
                {
                    Text = s.Nombre,
                    Value = s.IdSexo.ToString(),
                    Selected = false
                };
            });

            Persona resultado = AD_Persona.ObtenerPersona(idPersona);

            foreach (var item in lista)
            {
                if (item.Value.Equals(resultado.IdSexo.ToString()))
                {
                    item.Selected = true;
                }
            }
            ViewBag.items = lista;

            ViewBag.Nombre = resultado.Nombre + " " + resultado.Apellido;
            return View(resultado);
        }
        [HttpPost]
        public ActionResult DatosPersona(Persona model)
        {

            if (ModelState.IsValid)
            {
                bool resultado = AD_Persona.Actualizar(model);
                if (resultado)
                {
                    return RedirectToAction("ListaPersona", "Persona");
                }
                else
                {
                    return View(model);
                }
            }
            else
            {
                return View(model);
            }
        }
        public ActionResult EliminarPersona(int idPersona)
        {
            List<SexoItemVM> listaSexos = AD_Persona.obtenerListaSexos();

            List<SelectListItem> lista = listaSexos.ConvertAll(s =>
            {
                return new SelectListItem()
                {
                    Text = s.Nombre,
                    Value = s.IdSexo.ToString(),
                    Selected = false
                };
            });

            Persona resultado = AD_Persona.ObtenerPersona(idPersona);

            foreach (var item in lista)
            {
                if (item.Value.Equals(resultado.IdSexo.ToString()))
                {
                    item.Selected = true;
                }
            }
            ViewBag.items = lista;
            return View(resultado);
        }
        [HttpPost]
        public ActionResult EliminarPersona(Persona model)
        {

            if (ModelState.IsValid)
            {
                bool resultado = AD_Persona.Eliminar(model);
                if (resultado)
                {
                    return RedirectToAction("ListaPersona", "Persona");
                }
                else
                {
                    return View(model);
                }
            }
            else
            {
                return View(model);
            }
        }

    }
}

EjemploPersona/EjemploPersona/Controllers/ReporteController.cs
using EjemploPersona.ViewModel.Reportes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EjemploPersona.Controllers
{
    public class ReporteController : Controller
    {
        // GET: Reporte
        public ActionResult Index()
        {
            reporteGralVM resultado = new reporteGralVM();
            return View(resultado);
        }
    }
}

EjemploPersona/EjemploPersona/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

EjemploPersona/EjemploPersona/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EjemploPersona/EjemploPersona/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

EjemploPersona/EjemploPersona/Views/Persona/CargarPersona.cshtml
@model EjemploPersona.Models.Persona
@{
    ViewBag.Title = "CargarPersona";
}

<h2>CargarPersona</h2>

@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-lg-6">
            <div class="form-horizontal">
                <div class="form-group">
                    <label class="col-sm-6 control-label">
                        Nombre
                    </label>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(model => model.Nombre, htmlAttributes: new { @class = "form-control", @id = "txtNombre" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-6 control-label">
                        Apellido
                    </label>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(model => model.Apellido, htmlAttributes: new { @class = "form-control", @id = "txtApellido" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-6 control-label">
                        Dni
                    </label>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(model => model.Dni, htmlAttributes: new { @class = "form-control", @id = "txtDni" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-6 control-label">
                        Edad
                    </label>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(model => model.Edad, htmlAttributes: new { @class = "form-control", @id = "txtNombreUsuario" })
                    </div>
                </div>
                <div class="form-group text-right">
                    <div class="col-xs-12">
                        <button class="btn btn-primary" type="submit">Agregarr</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

EjemploPersona/EjemploPersona/Views/Persona/DatosPersona.cshtml
@model EjemploPersona.Models.Persona
@{
    ViewBag.Title = "Persona";
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;
}

<h2>Datos de la persona: @ViewBag.Nombre </h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.Id)
    <div class="row">
        <div class="col-lg-6">
            <div class="form-horizontal">
                <div class="form-group">
                    <label class="col-sm-6 control-label">
                        Nombre
                    </label>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(model => model.Nombre, htmlAttributes: new { @class = "form-control", @id = "txtNombre" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-6 control-label">
                        Apellido
                    </label>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(model => model.Apellido, htmlAttributes: new { @class = "form-control", @id = "txtApellido" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-6 control-label">
                        Sexo
                    </label>
                    <div class="col-sm-6">
                        @Html.DropDownList("IdSexo", items, "Seleccione sexo...", htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-6 control-label">
                        Dni
                    </label>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(model => model.Dni, htmlAttributes: new { @class = "form-control", @id = "txtDni" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-6 control-label">
                        Edad
                    </label>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(model => model.Edad, htmlAttributes: new { @class = "form-control", @id = "txtNombreUsuario" })
                    </div>
                </div>
                <div class="form-group text-right">
                    <div class="col-xs-12">
                        <button class="btn btn-primary" type="submit">
                            Actualizar datos
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

EjemploPersona/EjemploPersona/Views/Persona/EliminarPersona.cshtml
@model EjemploPersona.Models.Persona
@{
    ViewBag.Title = "Eliminar";
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;
}

<h2>Eliminar persona: @Model.Nombre @Model.Apellido </h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.Id)
    <div class="row">
        <div class="col-lg-6">
            <div class="form-horizontal">
                <div class="form-group">
                    <label class="col-sm-6 control-label">
                        Nombre
                    </label>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(model => model.Nombre, htmlAttributes: new { @class = "form-control", @id = "txtNombre" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-6 control-label">
                        Apellido
                    </label>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(model => model.Apellido, htmlAttributes: new { @class = "form-control", @id = "txtApellido" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-6 control-label">
                        Sexo
                    </label>
                    <div class="col-sm-6">
                        @Html.DropDownList("IdSexo", items, "Seleccione sexo...", htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-6 control-label">
                        Dni
                    </label>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(model => model.Dni, htmlAttributes: new { @class = "form-control", @id = "txtDni" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-6 control-label">
                        Edad
                    </label>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(model => model.Edad, htmlAttributes: new { @class = "form-control", @id = "txtNombreUsuario" })
                    </div>
                </div>
                <div class="form-group text-right">
                    <div class="col-xs-12">
                        <button class="btn btn-danger" type="submit">
                            Eliminar
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

EjemploPersona/EjemploPersona/Views/Persona/ListaPersona.cshtml
@model IEnumerable<EjemploPersona.Models.Persona>
@{
    ViewBag.Title = "Lista de Persona";
}

<h2>Listado de Personas cargados en la BD</h2>

<div class="row">
    <div class="col-lg-6">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th class="text-center">
                        Nombre
                    </th>
                    <th class="text-center">
                        Apellido
                    </th>
                    <th class="text-center">
                        Dni
                    </th>
                    <th class="text-center">
                        Edad
                    </th>
                    <th class="text-center">
                        Acciones
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var persona in Model)
                {
                <tr class="text-center">
                    <td>
                        @persona.Nombre
                    </td>
                    <td>
                        @persona.Apellido
                    </td>
                    <td>
                        @persona.Dni
                    </td>
                    <td>
                        @persona.Edad
                    </td>
                    <td>
                        <a href="@Url.Action("DatosPersona","Persona", new {@idPersona = persona.Id })" class="btn btn-success">Mostrar</a>
                        <a href="@Url.Action("EliminarPersona","Persona", new {@idPersona = persona.Id })" class="btn btn-danger">Eliminar</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

EjemploPersona/EjemploPersona/Views/Reporte/Index.cshtml
@model EjemploPersona.ViewModel.Reportes.reporteGralVM
@{
    ViewBag.Title = "Informe general";
}

<h2>Reporte info general</h2>

<div class="row">
    <div class="col-lg-6">
        <div class="col-lg-12">
            <div>
                <h3>
                    Personas por sexo
                </h3>
            </div>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th class="text-center">
                        Sexo
                    </th>
                    <th class="text-center">
                        Cantidad
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var sexo in Model.ListaSexo)
                {
                    <tr class="text-center">
                        <td>
                            @sexo.Nombre
                        </td>
                        <td>
                            @sexo.Cantidad
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-lg-6">
        <div class="col-lg-12">
            <div>
                <h3>
                    Lista de personas
                </h3>
            </div>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th class="text-center">
                        Nombre
                    </th>
                    <th class="text-center">
                        Apellido
                    </th>
                    <th class="text-center">
                        Dni
                    </th>
                    <th class="text-center">
                        Edad
                    </th>
                    <th class="text-center">
                        Sexo
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var persona in Model.ListaPersonas)
                {
                <tr class="text-center">
                    <td>
                        @persona.Nombre
                    </td>
                    <td>
                        @persona.Apellido
                    </td>
                    <td>
                        @persona.Dni
                    </td>
                    <td>
                        @persona.Edad
                    </td>
                    <td>
                        @persona.NombreSexo
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

EjemploPersona/EjemploPersona/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Agregar Persona", "CargarPersona", "Persona")</li>
                    <li>@Html.ActionLink("Listar Personas", "ListaPersona", "Persona")</li>
                    <li>@Html.ActionLink("Informe general", "Index", "Reporte")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>